Document: libipfix
Title: Debian libipfix Manual
Author: <insert document author here>
Abstract: This manual describes what libipfix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libipfix/libipfix.sgml.gz

Format: postscript
Files: /usr/share/doc/libipfix/libipfix.ps.gz

Format: text
Files: /usr/share/doc/libipfix/libipfix.text.gz

Format: HTML
Index: /usr/share/doc/libipfix/html/index.html
Files: /usr/share/doc/libipfix/html/*.html
