all: # nothing to build

install:
	mkdir -p $(DESTDIR)/usr/share/kafka
	mkdir -p $(DESTDIR)/etc/kafka
	cp -a bin $(DESTDIR)/usr/share/kafka
	cp -a libs $(DESTDIR)/usr/share/kafka
	cp -r config $(DESTDIR)/etc/kafka
